webtalk_init -webtalk_dir C:/Users/Hp/Desktop/Arkitektura_1_2_3/Arkitektura_1_2/Arkitektura_1.sim/sim_1/behav/xsim/xsim.dir/alu_32bit_tbb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 27 02:54:16 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7cdc5267-c360-4a60-a988-6349829b4717" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d0ca7dd96c2b440e9d2cb80b5305aa41" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "88" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A12-9730P RADEON R7, 10 COMPUTE CORES 4C+6G" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2795 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6192_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3359660045 -regid "" -xml C:/Users/Hp/Desktop/Arkitektura_1_2_3/Arkitektura_1_2/Arkitektura_1.sim/sim_1/behav/xsim/xsim.dir/alu_32bit_tbb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Hp/Desktop/Arkitektura_1_2_3/Arkitektura_1_2/Arkitektura_1.sim/sim_1/behav/xsim/xsim.dir/alu_32bit_tbb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Hp/Desktop/Arkitektura_1_2_3/Arkitektura_1_2/Arkitektura_1.sim/sim_1/behav/xsim/xsim.dir/alu_32bit_tbb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
